{
  "formatVersion": "1.1",
  "component": {
    "group": "host.exp.exponent",
    "module": "expo.modules.video",
    "version": "56.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "expo.modules.video-56.1.1.aar",
          "url": "expo.modules.video-56.1.1.aar",
          "size": 618601,
          "sha512": "6d102846d02920f6bd8dc97886737a23e131edfe4e8731d849541eea908fdadde4770034e89ef0885f8503b01633adf996f698df92c6043c4da19dd91fc60d3a",
          "sha256": "8281939eb84beea8189b53b8fb575e5037e7c632b4b7cf47494b71f3372d56b4",
          "sha1": "aa00a0cd8bb5adf7203df540a5dd3649c7ff41f1",
          "md5": "7f5a78024bc20e7cde3f411665d06592"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "com.facebook.react",
          "module": "react-android"
        },
        {
          "group": "androidx.media3",
          "module": "media3-session",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-okhttp",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.8.9"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.9"
          }
        },
        {
          "group": "io.github.lukmccall.pika",
          "module": "pika-api",
          "version": {
            "requires": "0.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "expo.modules.video-56.1.1.aar",
          "url": "expo.modules.video-56.1.1.aar",
          "size": 618601,
          "sha512": "6d102846d02920f6bd8dc97886737a23e131edfe4e8731d849541eea908fdadde4770034e89ef0885f8503b01633adf996f698df92c6043c4da19dd91fc60d3a",
          "sha256": "8281939eb84beea8189b53b8fb575e5037e7c632b4b7cf47494b71f3372d56b4",
          "sha1": "aa00a0cd8bb5adf7203df540a5dd3649c7ff41f1",
          "md5": "7f5a78024bc20e7cde3f411665d06592"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "expo.modules.video-56.1.1-sources.jar",
          "url": "expo.modules.video-56.1.1-sources.jar",
          "size": 74742,
          "sha512": "5e6c36390418bf2397ef0c6958e449df2888ea2dc501c0940b460b91a3bc926b12ff108d9f403a82d11eb8dfc92cca63775d13b676076c731b36d69fd86f602e",
          "sha256": "b19d3a35fa0e41fd0a8c871d44bc4a7764384bb0567be3301ade3bf0f38bbb26",
          "sha1": "ccd8650ee4d87fc0f6d9835bce077a8930139b44",
          "md5": "78ea3c6217d3be86fae6a74044e45192"
        }
      ]
    }
  ]
}
