const colors = {
  light: {
    text: "#0e0f0c",
    tint: "#ff5f1f",
    background: "#f0f0e8",
    foreground: "#0e0f0c",
    card: "#e8e8de",
    cardForeground: "#0e0f0c",
    primary: "#ff5f1f",
    primaryForeground: "#ffffff",
    secondary: "#e2e2d8",
    secondaryForeground: "#0e0f0c",
    muted: "#d8d8ce",
    mutedForeground: "#8a8a7e",
    accent: "#ff5f1f",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#d0d0c4",
    input: "#d0d0c4",
    darkCard: "#1a1a16",
    darkCardText: "#ffffff",
    orange: "#ff5f1f",
    rankGold: "#f5c842",
    rankDiamond: "#60c8ff",
    rankPlatinum: "#c8a8e8",
    rankLegend: "#9fe870",
  },
  radius: 24,
};

export default colors;
