import { Router, type IRouter } from "express";
import healthRouter from "./health";
import usersRouter from "./users";
import gamesRouter from "./games";
import challengesRouter from "./challenges";
import momentsRouter from "./moments";
import leaguesRouter from "./leagues";
import friendsRouter from "./friends";
import leaderboardRouter from "./leaderboard";
import commentsRouter from "./comments";
import savesRouter from "./saves";
import dislikesRouter from "./dislikes";
import inboxRouter from "./inbox";
import reactionsRouter from "./reactions";
import reportsRouter from "./reports";
import ballsRouter from "./balls";
import scorecardRouter from "./scorecard";
import alleysRouter from "./alleys";

const router: IRouter = Router();

router.use(healthRouter);
router.use(usersRouter);
router.use(scorecardRouter);
router.use(gamesRouter);
router.use(challengesRouter);
router.use(momentsRouter);
router.use(leaguesRouter);
router.use(friendsRouter);
router.use(leaderboardRouter);
router.use(commentsRouter);
router.use(savesRouter);
router.use(dislikesRouter);
router.use(inboxRouter);
router.use(reactionsRouter);
router.use(reportsRouter);
router.use(ballsRouter);
router.use(alleysRouter);

export default router;
